# Generated by Django 3.1.7 on 2021-02-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20210223_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='gender',
            field=models.CharField(max_length=6, null=True, verbose_name='성별'),
        ),
    ]
